spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-34-230-110-100.compute-1.amazonaws.com:5432/d94m5td3mj4kfk?user=jgdietsilpesrz&password=10d2200537c7c13d60e42add6a39ea47a6ee2abb1e0dd556d673f5c01e0cebad
    driver-class-name: org.postgresql.Driver
    username:
    password:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: INFO