spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: public
        temp:
          use_jdbc_metadata_default: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/agro_online
    username: postgres
    password: 10d2200537c7c13d60e42add6a39ea47a6ee2abb1e0dd556d673f5c01e0cebad
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

  messages:
    basename: bundles/apiLanguageBundle

logging:
  level:
    root: INFO
  file: akatsuki.log

